---
- name: Delete apache Tomcat10 on ubuntu
  hosts: ngnix-hosts
  become: true

  tasks: 
    - name: Stop Service tomcat
      ansible.builtin.service:
        name: tomcat
        state: stopped

    - name: Delete tomcat service
      ansible.builtin.file:
        path: /etc/systemd/system/tomcat.service
        state: absent

    - name: Delete tomcat instalation directory
      ansible.builtin.file:
        path: /opt/tomcat/apache-tomcat-10.0.0
        state: absent

    - name: Remove the Tomcat user and group
      ansible.builtin.user:
        name: tomcat
        state: absent
      ignore_errors: true